# Generated by Django 5.2.8 on 2025-12-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_seed_exchange_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
    ]
