# Generated by Django 5.2.8 on 2026-01-27 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_expensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Upload receipt image or PDF (optional)', null=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
