# Generated by Django 5.2.8 on 2025-11-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('licensePlate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('currentMileage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'Under Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Insurance', 'Insurance'), ('Service', 'Service'), ('License', 'License'), ('Other', 'Other')], max_length=20)),
                ('dueDate', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('emailNotifications', models.BooleanField(default=False)),
                ('notificationEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('notificationFrequency', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20, null=True)),
                ('notificationDaysBefore', models.IntegerField(blank=True, default=1, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='fleet.vehicle')),
            ],
        ),
    ]
