# Generated by Django 5.2.8 on 2025-11-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('recipientEmail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('errorMessage', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sentAt'],
            },
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['dueDate']},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='emailNotifications',
            new_name='emailNotification',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='notificationEmail',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='notificationFrequency',
        ),
        migrations.AddField(
            model_name='reminder',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='lastNotificationSent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notificationDaysBefore',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['dueDate', 'status'], name='fleet_remin_dueDate_d95447_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['emailNotification'], name='fleet_remin_emailNo_91642b_idx'),
        ),
        migrations.AddField(
            model_name='remindernotification',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.reminder'),
        ),
    ]
