# Generated by Django 5.2.8 on 2025-11-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('driver', 'Driver'), ('employee', 'Employee')], default='driver', max_length=20),
        ),
    ]
